import type { Metadata } from 'next';
import './globals.css';
import { zenKurenaido } from './utils/fonts';
import Footer from './_components/(footer)/footer';
import * as C from './_components/(cookies)/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body
        className={`w-full h-auto bg-cafe-cream text-cafe-text ${zenKurenaido.className}`}
      >
        {children}
        <Footer />
        <C.LeftSideCookie />
        <C.RightSideCookie />
      </body>
    </html>
  );
}
